### ISSUE TITLE
[perception] Remove hardcoded orientation in mir_handle_detection

### ISSUE THREAD

**Issue by DharminB** [b-it-bots/mas_industrial_robotics#102]
Currently the orientation of the handle in `mir_handle_detection` is hardcoded. It needs to be calculated. The normal of the plane of the drawer should be used as orientation.

This orientation can later be used to align the robot perpendicular to the drawer surface rather than assuming that it is parallel.

**Additional context**
https://github.com/b-it-bots/mas_industrial_robotics/pull/99#discussion_r375799789

**Comment by sthoduka** [comment]
@iswariyam do you want to look into this?

**Comment by iswariyam** [comment]
@sthoduka  Yes I will look into it.

**Comment by sthoduka** [comment]
Fixed in #108
