### ISSUE TITLE
[pick_from_drawer] update planning domain

### ISSUE THREAD

**Issue by sthoduka** [b-it-bots/mas_industrial_robotics#117]
To incorporate picking from a drawer, some more actions need to be added to the [task planning domain](https://github.com/b-it-bots/mas_industrial_robotics/blob/kinetic/mir_planning/mir_knowledge/common/pddl/general_domain/domain.pddl).

I think this would be at least `open` and `close`, but probably also a new `perceive` action which has a precondition that the drawer is open.

The actions to pick from a drawer might look like:
1. `perceive`
2. `open`
3. `pick`
4. `stage`
5. `close`

We might also want to add actions for putting objects back in the drawer.

The [docs](https://github.com/b-it-bots/mas_industrial_robotics/tree/kinetic/docs) should have everything you need to get task planning running independent of the robot.
cc: @DharminB

**Comment by deebuls** [comment]
@sthoduka Since these are smaller objective shouldn't we just do it using python script planning rather than task planning. 
Its like too much time for a problem which will not be there forever.
