### ISSUE TITLE
[task planning] visualize KB and task plan 

### ISSUE THREAD

**Issue by sthoduka** [b-it-bots/mas_industrial_robotics#118]
We want to visualize two things
1. the facts and goals in the knowledge base. This includes locations of objects, their target destinations, state of the robot's rear platform, whether an object is in the gripper, etc.
2. the task plan 

Using Rviz markers might be the best way to do this. CAD models of all objects are available [here](https://github.com/robocup-at-work/models) (rviz can be used to display [meshes](https://wiki.ros.org/rviz/DisplayTypes/Marker#Mesh_Resource_.28MESH_RESOURCE.3D10.29_.5B1.1.2B-.5D))

**Comment by DharminB** [comment]
I am working on knowledge base visualisation. @iswariyam, maybe, you can take a look into visualisation of task plan. I am thinking of creating a single package named something like `mir_planning_visualisation` in `mas_industrial_robotics/mir_planning/` folder. I will create a PR with WIP shortly. If you want I can give you write access to my fork. :man_shrugging:
