### ISSUE TITLE
[Presentation] Prepare presentation for champions paper

### ISSUE THREAD

**Issue by deebuls** [b-it-bots/mas_industrial_robotics#151]
- Decide on speakers
- Decide on the format
- Decide on content
 
location will be here https://github.com/b-it-bots/competition-documents

**Comment by deebuls** [comment]
I would suggest present the champions paper.

@DharminB  @HAndradi  @1apple7seeds  @iswariyam  @RaghuvirShirodkar @DeepanChakravarthiPadmanabhan

**Comment by sthoduka** [comment]
added [template](https://github.com/b-it-bots/competition-documents/tree/master/presentations/gkk-symposium-champions-talk)

**Comment by deebuls** [comment]
How we won the Sciroc competition.

- hardware - @RaghuvirShirodkar 
- sw architecture @iswariyam 
- navigation  @HAndradi 
- perception @HAndradi @DeepanChakravarthiPadmanabhan 
- manipulation @1apple7seeds , @RaghuvirShirodkar 
- planning @DharminB

**Comment by deebuls** [comment]
Please provide the initial draft video .
4th September - 1st draft
11th September - Final version

**Comment by deebuls** [comment]
Please use this to record your videos. Its web based select the presentation in one side and your webcam feed on other side.

https://studio.opencast.org/
