### ISSUE TITLE
Precision Placement Test (PPT)

### ISSUE THREAD

**Issue by kvnptl** [b-it-bots/mas_industrial_robotics#267]
Test the implementation of PPT

**Comment by kvnptl** [comment]
Did you try with the "arm camera"?

**Comment by kvnptl** [comment]
> Did you try with the "arm camera"?

Using only tower camera

**Comment by kvnptl** [comment]
Perception fixed for PPT
- Cavity recognition using only RGB image

**Comment by kvnptl** [comment]
The pipeline is ready and tested.

TODO: fix the yaw error while placing

**Comment by kvnptl** [comment]
Yaw error is fixed, now using without sampling poses.

**Comment by RavisankarSelvaraju** [comment]
PPT post placing wiggle strategies are implemented
-  rotational wiggle is working and tested
- linear wiggle is not working as expected while running via full pipeline ATT tasks
