### ISSUE TITLE
Rotating Table Test (RTT)

### ISSUE THREAD

**Issue by kvnptl** [b-it-bots/mas_industrial_robotics#268]
Implement RTT on yb2

**Comment by michal-stolarz** [comment]
Here is the repository for the Sort tracker with Yolov5 as a backbone: https://github.com/VincentSch4rf/rtt_tracking . To run the tracker please use the `not_main.py` file in the `nanonets_object_tracking` directory. To run the evaluation, please run `eval_metrics.py` file. The dataset is available under: https://github.com/VincentSch4rf/RoboCup-RTT-Dataset .

**Comment by kvnptl** [comment]
One object seems to be working now, but not yet tested with Refbox

**Comment by kvnptl** [comment]
TODO: 
- make it work with multiple objects
- re-perceive if missed on the first try
