### ISSUE TITLE
Design a staging area for yb2 configuration

### ISSUE THREAD

**Issue by kvnptl** [b-it-bots/mas_industrial_robotics#270]
- design should be capable of holding 3 objects

**Comment by gokulkchenchani** [comment]
Initial workflow design:

![IMG_20230217_182329](https://user-images.githubusercontent.com/81406273/219722946-13c4e95a-2a05-436b-b7a6-ee13d1251ae0.jpg)

**Comment by RavisankarSelvaraju** [comment]
initial test design with preliminary tests proves sufficient for the staging area. 
Todo:
- Reduce material in the staging area design 
- Find a material/board to fix the staging areas to the platform 
- adjust the staging area design as suggested by @KishanSawant

**Comment by kvnptl** [comment]
Could you upload some screenshots here of the design or printed design?

**Comment by RavisankarSelvaraju** [comment]
![01](https://github.com/b-it-bots/mas_industrial_robotics/assets/91879299/fd40a034-1b46-4b57-931e-665a33d727d3)
![02](https://github.com/b-it-bots/mas_industrial_robotics/assets/91879299/1b651e95-2fce-4b9a-a8dc-ed719acb62ac)
![03](https://github.com/b-it-bots/mas_industrial_robotics/assets/91879299/bb01e531-5cce-4695-967f-86c15c66f3f5)

**Comment by kvnptl** [comment]
TODO: update a real robot picture with a staging area here

**Comment by gokulkchenchani** [comment]
- Final Staging area fixed on YouBot2.
![IMG_20230617_114455](https://github.com/b-it-bots/mas_industrial_robotics/assets/81406273/0dfbe077-66f7-463d-9fac-307b142d9bff)
