### ISSUE TITLE
Grasp verification during unstaging

### ISSUE THREAD

**Issue by kvnptl** [b-it-bots/mas_industrial_robotics#271]

**Comment by RavisankarSelvaraju** [comment]
![IMG_20230324_141857.jpg](https://user-images.githubusercontent.com/91879299/227531256-1c908c15-f312-4a51-910c-28aa3cd3f215.jpg)

![IMG_20230324_141905.jpg](https://user-images.githubusercontent.com/91879299/227531257-f259f945-56d4-4c5f-93d8-55a37682475b.jpg)

**Comment by kvnptl** [comment]
Is it integrated and tested well?

**Comment by RavisankarSelvaraju** [comment]
The grasp verification is implemented during unstaging and it will retries 3 times. but other failure recovery stratesies are not implemented yet.

**Comment by kvnptl** [comment]
So if the robot picks up and stages a ghost object, then the robot would try to unstage it 3 times and then move to the next task. Is it correct?

**Comment by kvnptl** [comment]
https://github.com/b-it-bots/mas_industrial_robotics/issues/297

**Comment by kvnptl** [comment]
#297

**Comment by kvnptl** [comment]
related #297

**Comment by RavisankarSelvaraju** [comment]
> So if the robot picks up and stages a ghost object, then the robot would try to unstage it 3 times and then move to the next task. Is it correct?

This is the observed behaviour during one  of the recent runs. I haven't looked into the code yet. I can update on this tomorrow
