### ISSUE TITLE
Battery adapter design

### ISSUE THREAD

**Issue by kvnptl** [b-it-bots/mas_industrial_robotics#272]
- For Derby cycle battery - [Link](https://akku4bikes.de/produkt/e-bike-akku-26v-24ah-fuer-flyer-kalkhoff-kettler/)

**Comment by RavisankarSelvaraju** [comment]
#296 Upload the designs

**Comment by kvnptl** [comment]
@GokulKrishna02 take wires out from the old adapter, and test it 

Close this issue once done
