### ISSUE TITLE
Barrier tape detection 

### ISSUE THREAD

**Issue by kvnptl** [b-it-bots/mas_industrial_robotics#274]
- Test the implementation of barrier tape detection
- Check the hardware compatibility with the existing design
- Verify the navigation stack with this implementation

**Comment by gokulkchenchani** [comment]
- Barrier tape detection standalone implementation tested and verified.
- Barrier tape detection verified with navigation stack during BMT run with back camera.

**Comment by gokulkchenchani** [comment]
- Barrier tape detection verified with navigation stack during mini BMT run with both front and back camera.
