### ISSUE TITLE
Add camera's tower in URDF 

### ISSUE THREAD

**Issue by kvnptl** [b-it-bots/mas_industrial_robotics#278]
- For yb2 configuration

**Comment by kvnptl** [comment]
![image](https://user-images.githubusercontent.com/47410011/227615604-f2472a37-83c3-4201-b4a2-fdacd614711b.png)

- Added camera tower in URDF - @vamsikalagaturu 
- Added 3 camera mounts - @kvnptl 
- Added emergency stop button mount - @kvnptl

**Comment by vamsikalagaturu** [comment]
Convert the STL files into DAE files

**Comment by kvnptl** [comment]
Commit all the relevant CAD files to the respective repository
