### ISSUE TITLE
Test BMT using refbox

### ISSUE THREAD

**Issue by kvnptl** [b-it-bots/mas_industrial_robotics#280]
- Run `mini_bmt_demo` with refbox

**Comment by RavisankarSelvaraju** [comment]
The previous ref box is working fine and generating the plan, but the new ref box (2023 with ATT tasks) is not working as of my last test

**Comment by kvnptl** [comment]
Is the issue still there for ATT tasks?

**Comment by RavisankarSelvaraju** [comment]
The ATT is not tested as of now. I am closing this since BMT is tested and working fine with refbox
