### ISSUE TITLE
youbot arm initialization error | yb2

### ISSUE THREAD

**Issue by kvnptl** [b-it-bots/mas_industrial_robotics#283]
## Steps to Reproduce

1. `roslaunch mir_bringup robot.launch`

## Expected Behavior

On launching `bringup`, it gives the below error message:

```
[FATAL] [1677075113.807641982] [/youbot_driver_ros_interface]: Not enough ethercat slaves were found to create a YouBotManipulator!
[ERROR] [1677075113.807662217] [/youbot_driver_ros_interface]: Arm "youbot-manipulator" could not be initialized.
```

## Environment

* Version used (branch/commit):
* PC:
    - [x] on the robot (if applicable specify which one)
    - [x] robot's setup
        * OS: Ubuntu 20.04
        * ROS version: Noetic

**Comment by vamsikalagaturu** [comment]
The ethernet board was defective and was replaced on the ybrsu-2. The issue is resolved with it.
