### ISSUE TITLE
[Dataset collection] new Dataset for RoboCup2023

### ISSUE THREAD

**Issue by kvnptl** [b-it-bots/mas_industrial_robotics#293]
- 7 basic object set (existing)
- 9 advanced object set (new)

Total: 16 objects

**Comment by kvnptl** [comment]
**Basic object set** (7 objects)

![image](https://github.com/b-it-bots/mas_industrial_robotics/assets/47410011/2eec19b1-9998-462c-ae28-31a961831382)

**Comment by kvnptl** [comment]
**Advanced object set** (9 objects)

![image](https://github.com/b-it-bots/mas_industrial_robotics/assets/47410011/9589d6d2-73a4-4f49-bcbf-c66094cc04f0)

![image](https://github.com/b-it-bots/mas_industrial_robotics/assets/47410011/98947ef7-f49f-49d2-adc4-e8209400c91e)

**Comment by kvnptl** [comment]
- Please find the sheets for dataset collection (set1 and set2) [HERE, BIB-CLOUD](https://bib-cloud.bib.hochschule-bonn-rhein-sieg.de/apps/files/?dir=/Shared/b-it-bots-ds/atwork/images/object_detection/YOLO/robocup_2023_dataset/dataset_collection&fileid=16051529)
- Dataset collection id  allotment [HERE](https://bib-cloud.bib.hochschule-bonn-rhein-sieg.de/apps/files/?dir=/Shared/b-it-bots-ds/atwork/images/object_detection/YOLO/robocup_2023_dataset/dataset_collection&openfile=16051640)

Let me know, if you have any doubts

**Comment by gokulkchenchani** [comment]
- 0 - 154 dataset collection from set 2 completed and updated [HERE](https://bib-cloud.bib.hochschule-bonn-rhein-sieg.de/apps/files/?dir=/Shared/b-it-bots-ds/atwork/images/object_detection/YOLO/robocup_2023_dataset/dataset_collection/Dataset_set2_0_to_154&fileid=16183934).
- Dataset collected on different surfaces and on RTT and shelf.

**Comment by kvnptl** [comment]
**Guidelines for data collection:**
1. Keep the camera on a tripod
    - Maintain the same height and angle as Youbot's front camera 
3. Use `rosrun image_view image_view image:=<image topic>` to see camera feed
   - Use right-click to save images (NOTE: saved image names start from frame0000)
   - Rename the images according the id(s) given in the sheet (set1 or set2)
   - Make sure to have intel realsense ROS package; if not, install `sudo apt-get install ros-$ROS_DISTRO-realsense2-camera`
   - Launch camera `roslaunch realsense2_camera rs_camera.launch` on different terminal
4. Keep the lights ON in the room
5. Use different surfaces
    - <img src="https://github.com/b-it-bots/mas_industrial_robotics/assets/47410011/a574e86d-ff37-44df-a212-0f69debbfbda" width="500">
6. Use DECOY objects with our at-work objects, as shown in the image
    - <img src="https://github.com/b-it-bots/mas_industrial_robotics/assets/47410011/0173cf9d-ae8a-4a53-934e-4f2c1e78afc1" width="500">

7. Regarding where and how to place objects on the workstation
    - **Where**: keep objects in the 20 cm range on the workstation [check the below image]
    - **How**: keep at least 2 cm gap between the objects [check the below image]
    - <img src="https://github.com/b-it-bots/mas_industrial_robotics/assets/47410011/73eaf978-2719-4e63-ab8d-2426ceadee5d" width="500">

**Comment by kvnptl** [comment]
- IDs 308 to 461, dataset collection from set 1 and set 2 completed and updated [HERE](https://bib-cloud.bib.hochschule-bonn-rhein-sieg.de/apps/files/?dir=/Shared/b-it-bots-ds/atwork/images/object_detection/YOLO/robocup_2023_dataset/dataset_collection/KEVIN_RAVI&fileid=16214720).

**Comment by kvnptl** [comment]
- Use [file_renaming.py](https://bib-cloud.bib.hochschule-bonn-rhein-sieg.de/apps/files/?dir=/Shared/b-it-bots-ds/atwork/images/object_detection/YOLO/robocup_2023_dataset/dataset_collection&openfile=16217151) script for renaming files

**Comment by kvnptl** [comment]
[UPDATE]

The initial YOLOv8(s) model trained on image ids 308-461 (both sets) is ready to use for further annotation. Please find the trained model [HERE](https://bib-cloud.bib.hochschule-bonn-rhein-sieg.de/apps/files/?dir=/Shared/b-it-bots-ds/atwork/images/object_detection/YOLO/robocup_2023_dataset/dataset_collection/01_Trained_Models&fileid=16267283).

In order to use the custom trained model in `anylabeling` tool,
1. Download the ONNX and YAML files from [HERE](https://bib-cloud.bib.hochschule-bonn-rhein-sieg.de/apps/files/?dir=/Shared/b-it-bots-ds/atwork/images/object_detection/YOLO/robocup_2023_dataset/dataset_collection/01_Trained_Models&fileid=16267283)
    - NOTE: keep both files in the same directory
2. In `anylabeling` tool, click on "Auto Labeling" icon -> from the drop-down menu, select "Load Custom Model" -> select the downloaded YAML file.
3. Don't forget to verify the annotations and correct them (labels and bbox) if required

Please let me know if you face any issues.

**Comment by gokulkchenchani** [comment]
- 0 - 154 set 2 annotations completed and updated [HERE](https://bib-cloud.bib.hochschule-bonn-rhein-sieg.de/apps/files/?dir=/Shared/b-it-bots-ds/atwork/images/object_detection/YOLO/robocup_2023_dataset/dataset_collection/GOKUL_VIVEK/set2_000_154_annotated&fileid=16260155).

**Comment by kvnptl** [comment]
[FINAL UPDATE]

- Dataset collection completed
- Dataset annotation completed

=> **Find the full dataset [HERE](https://bib-cloud.bib.hochschule-bonn-rhein-sieg.de/apps/files/?dir=/Shared/b-it-bots-ds/atwork/images/object_detection/YOLO/robocup_2023_dataset&fileid=16051420)**
