### ISSUE TITLE
Push all the 3D designs and STL files to a common repo/bibcloud

### ISSUE THREAD

**Issue by RavisankarSelvaraju** [b-it-bots/mas_industrial_robotics#296]

**Comment by RavisankarSelvaraju** [comment]
Upload the designs [here](https://bib-cloud.bib.hochschule-bonn-rhein-sieg.de/f/16305159)!

**Comment by kvnptl** [comment]
Uploaded Derby cycle adaptor designs

**Comment by kvnptl** [comment]
@GokulKrishna02 add camera mounts design and emergency stop button on the bib cloud

**Comment by gokulkchenchani** [comment]
Uploaded below designs to bibcloud:
- back camera mount
- front camera mount
- battery adapter
- emergency switch mount

**Comment by kvnptl** [comment]
Pending designs to upload:
- staging area - @RavisankarSelvaraju 
- gripper finger mount - @RavisankarSelvaraju 
- gripper design (flexible material design) - @RavisankarSelvaraju 
- battery base mount - @GokulKrishna02
- gripper controller mount - @GokulKrishna02 
- gripper mount - @GokulKrishna02

**Comment by kvnptl** [comment]
Gripper controller mount

<p align="left">
  <img src="https://github.com/b-it-bots/mas_industrial_robotics/assets/47410011/2da1991f-03aa-48c0-a0fe-ece035a7e4ac" width=40% />
  <br></br>
</p>

**Comment by RavisankarSelvaraju** [comment]
- Staging area design 
- Gripper finger mount 
- gripper design 

these 3 design are updated in bib cloud

**Comment by gokulkchenchani** [comment]
Uploaded below designs to bibcloud:
- battery base mount
- gripper controller mount 
- gripper mount
