### ISSUE TITLE
Travis CL integration for mas industrial robotics branch

### ISSUE THREAD

**Issue by deebuls** [b-it-bots/mas_industrial_robotics#43]
Need to integrate travis CI for testing of the software.

Different methods are available:

1. Docker based
2. ROS industrial based
3. https://github.com/tdenewiler/node_example

**Comment by argenos** [comment]
If you need help with the docker option, let me know

**Comment by Sushant-Chavan** [comment]
Pull request #84 created to setup the Travis builds.

**Comment by Sushant-Chavan** [comment]
Travis CI is now setup in the PR #84. @deebuls Do you need a docker based build as well or can this issue be closed?

**Comment by Sushant-Chavan** [comment]
Created PR #92 to build a docker image using Travis CI and deploy to Docker Hub
