### ISSUE TITLE
Missing dependencies during catkin build

### ISSUE THREAD

**Issue by DharminB** [b-it-bots/mas_industrial_robotics#51]
- `ros-kinetic-brics-actuator`
- `orocos_kdl`
- `ros-kinetic-bfl`
- `libsvm-dev`
- `ros-kinetic-tf2-bullet`
- `ros-kinetic-mongodb-store`
- `flex`

**Comment by Sushant-Chavan** [comment]
This should be fixed after the CI builds were activated in the PR #84
