### ISSUE TITLE
New Navigation Simulation from NVIDIA

### ISSUE THREAD

**Issue by abhishekpadalkar** [b-it-bots/mas_industrial_robotics#80]
Here is the ISAAC SIM for navigation from NVIDIA . Might be useful but someone needs to integrate it. [https://developer.nvidia.com/isaac-sim](https://developer.nvidia.com/isaac-sim)

**Comment by mhwasil** [comment]
plus : GPU-accelerated  DNNs including object detection and multi-class segmentation, 3D object  pose estimation, and 2D skeleton pose estimation; Transfer Learning  Toolkit integrated to accelerate neural network training
