### ISSUE TITLE
Continuous integration of mir docs into b-it-bots wiki

### ISSUE THREAD

**Issue by mhwasil** [b-it-bots/mas_industrial_robotics#91]
Can we automatically push the built docs into [b-it-bots wiki](https://github.com/b-it-bots/wiki)? @Sushant-Chavan 

related to #78

**Comment by Sushant-Chavan** [comment]
The built docs change their version number every time a mas_industrial_robotics get a new commit. This will cause a new commit to be pushed to the wiki repository where the difference is only in the version number as shown [here](https://github.com/Sushant-Chavan/wiki/commit/2fcce1c66d205945c1cfaf0ed63016a5718baf65). @mhwasil  how to avoid these version changes?

**Comment by mhwasil** [comment]
The version of the docs is generated through [this function](https://github.com/b-it-bots/mas_industrial_robotics/blob/a7d77b2da55557fcc46d85fc641e99250f218f9f/docs/source/conf.py#L32).
The version of the docs should be the stable one, but since we do not have any release yet, I just take the latest version.

**Comment by Sushant-Chavan** [comment]
@mhwasil So can we hardcode this version for now?

**Comment by mhwasil** [comment]
Yes, we will fix this once we have the release.

**Comment by Sushant-Chavan** [comment]
Discussed the documentation versioning with @sthoduka and concluded that we will use the version name as `Kinetic` instead of the git commit hash id. This will avoid unnecessary commits in the `wiki` repository which could only be a change in the documentation version.

cc @mhwasil
